# Generated by Django 4.2.3 on 2023-07-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(default='1994-02-21'),
            preserve_default=False,
        ),
    ]
